# -*- coding: utf-8 -*-
"""TTS_module.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18u21FPU04UlOUGAG0f7touGbSXoEfOj-
"""

!pip install gTTS
from gtts import gTTS
from IPython.display import Audio

# Your text
text = """
Abstract—Dark patterns manipulate user choices through deceptive UI tactics. Any automated detection technique for dark patterns must address the varying nature of dark patterns. Existing detection techniques need manual intervention in some cases. In other cases, techniques are not generalized due to overfitting problems;
"""
# Generate and save
tts = gTTS(text, lang='en', tld='com.ng',)
tts.save("output.mp3")

# Play in notebook
Audio("output.mp3")